name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      #################################################
      # 1) CHECK OUT CODE
      #################################################
      - name: Check out repository
        uses: actions/checkout@v3

      #################################################
      # 2) BUILD & PUSH DOCKER IMAGE TO DOCKER HUB
      #################################################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build & Push Docker image
        id: buildpush
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # We'll tag the image with the commit SHA for uniqueness
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/telegram-chatbot:${{ github.sha }}

      #################################################
      # 3) AUTHENTICATE WITH GOOGLE CLOUD
      #################################################
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CLOUD_RUN_DEPLOY_SA_KEY }}

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Enable Cloud Run API
        run: |
            gcloud services enable run.googleapis.com --project ${{ secrets.GCP_PROJECT_ID }}

      #################################################
      # 4) DEPLOY TO CLOUD RUN
      #################################################
      - name: Deploy to Cloud Run
        run: |
          # Name of your Cloud Run service:
          SERVICE_NAME="telegram-chatbot"

          # The Docker image we built and pushed:
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/telegram-chatbot:${{ github.sha }}"

          # Deploy:
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE" \
            --port 8080 \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},TELEGRAM_BOT_FIRESTORE_SA_KEY_BASE64=${{ secrets.TELEGRAM_BOT_FIRESTORE_SA_KEY_BASE64 }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      #################################################
      # 5) SHOW RESULT
      #################################################
      - name: Show Service URL
        run: |
          SERVICE_NAME="telegram-chatbot"
          URL=$(gcloud run services describe "$SERVICE_NAME" \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --format 'value(status.url)')
          echo "Your Cloud Run service is deployed at: $URL"
          echo "Set your Telegram webhook to $URL/telegram/webhook"
